name: Deploy to Azure
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registry:
    if: false
    name: Push Docker image
    runs-on: ubuntu-latest
    environment: Azure
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: michalmoudry/newsletter-platform

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Azure
    #needs: [push_to_registry]
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: https://hub.docker.com/michalmoudry/newsletter-platform:latest
          resourceGroup: newsletter-platform